Replace usage of deprecated constants
sockless-coding/panasonic_cc pull request #155
Opened 2024-01-06 17:53 UTC by karlrank

Magic number constants have been deprecated and will be removed in 2025.1. These deprecations are now causing warnings in Home Assistant logs.

This PR fixes the deprecations by using the new approach

See: https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

2024-01-09 17:14 UTC, killer0071234 approved these changes

2024-01-09 20:02 UTC, codyc1515 approved these changes
LGTM

2024-06-29 22:51 UTC, codyc1515 commented
This was fixed in https://github.com/sockless-coding/panasonic_cc/pull/165 already, so can be closed.

2024-06-29 22:51 UTC, codyc1515 reviewed
This was fixed in https://github.com/sockless-coding/panasonic_cc/pull/165 already, so can be closed.

2024-06-29 22:51 UTC, codyc1515 requested changes
This was fixed in https://github.com/sockless-coding/panasonic_cc/pull/165 already, so can be closed.

2024-06-30 08:57 UTC, closed without merging